import { createHash, createCipheriv, randomBytes } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = join(__dirname, '..', 'dist');
const ASSETS = join(DIST, 'assets');
const INDEX = join(DIST, 'index.html');
const RUST_OUT = join(__dirname, '..', 'src-tauri', 'src', 'encrypted_assets.rs');

// Must match Rust: sha256("ragnarok-build-key-2024")[..32]
const KEY = createHash('sha256').update('ragnarok-build-key-2024').digest();

function encrypt(buf) {
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', KEY, iv);
  const enc = Buffer.concat([cipher.update(buf), cipher.final()]);
  const tag = cipher.getAuthTag();
  // Format: [iv(12)][ciphertext][tag(16)] — Rust decrypt_in_place expects tag after ciphertext
  return Buffer.concat([iv, enc, tag]);
}

function main() {
  const html = readFileSync(INDEX, 'utf-8');

  // Find the <script> tag for the main JS
  const scriptRegex = /<script[^>]*src="([^"]+\.js)"[^>]*><\/script>/i;
  const match = scriptRegex.exec(html);
  if (!match) {
    console.error('[encrypt] No script src found in index.html');
    process.exit(1);
  }

  const fullTag = match[0];
  const srcPath = match[1];
  const filename = srcPath.replace(/^\//, '');
  const filepath = join(DIST, filename);

  console.log(`[encrypt] Encrypting: ${filename}`);

  const content = readFileSync(filepath);
  const encrypted = encrypt(content);

  // Generate Rust source with embedded encrypted bytes
  const hex = encrypted.toString('hex');
  const len = encrypted.length;
  const rustCode = `// Auto-generated by scripts/encrypt-build.mjs — DO NOT EDIT
#![allow(dead_code)]
pub const ENCRYPTED_JS: &[u8] = b"${hex}";
`;
  writeFileSync(RUST_OUT, rustCode);

  // Replace script tag in index.html with inline loader
  const loader = `<script>
(async function(){
  try {
    var r=await window.__TAURI__.invoke('decrypt_asset');
    window.__TAURI__.invoke('show_main_window');
    (new Function(r))();
  }catch(e){
    console.error('[loader] decrypt failed:',e);
    document.body.innerHTML='<div style="display:flex;align-items:center;justify-content:center;height:100vh;background:#06060a;color:#888;font-family:sans-serif;font-size:14px">Error al cargar la aplicaci\u00f3n</div>';
    try{window.__TAURI__.invoke('show_main_window')}catch(_){}
  }
})();
</script>`;
  const modifiedHtml = html.replace(fullTag, loader);
  writeFileSync(INDEX, modifiedHtml);

  console.log('[encrypt] index.html updated with encrypted loader');
  console.log(`[encrypt] Generated ${RUST_OUT} (${len} bytes encrypted)`);
  console.log('[encrypt] Done.');
}

main();
